#application configuration
spring:
  application:
    name: bulk-upload
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mariadb://localhost:3306/bulkupload
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  servelet:
    multipart:
      enabled: true
      file-size-treshold: 2KB
      max-file-size: 20MB
      max-request-size: 20MB
